# Generated by Django 3.1.7 on 2021-04-01 07:12

import django.core.validators
from django.db import migrations, models
import src.webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210325_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
        migrations.AddField(
            model_name='postrate',
            name='rate',
            field=models.IntegerField(default=1, validators=[src.webapp.validators.rate_check], verbose_name='Нравится или нет'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=31, unique=True, verbose_name='Тег'),
        ),
    ]
